<?php
namespace Bo\AdminBundle\Repository;
use Bo\AdminBundle\Entity\Activities;
/**
 * ActivitiesRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivitiesRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTotal(){
		$query = $this->_em->createQuery('SELECT COUNT(a) From BoAdminBundle:Activities a');
		return (int) $query->getSingleScalarResult();
	}
	public function recordActitivy($rubric,$ssrub,$userid){
        $activity = new Activities();
		$activity->setRubric($rubric);
		$activity->setSubrubric(trim($ssrub));
		$activity->setUser($userid);
		$entityManager = $this->_em->getRepository('BoAdminBundle:Activities');
		$this->_em->persist($activity);
        $this->_em->flush();	
		return;
	}
	public function search($sTexte){
		$sSelect = "SELECT v FROM Bo\AdminBundle\Entity\Activities v  WHERE v.creationdate like :motcle or v.subrubric like :motcle or v.rubric like :motcle or v.sessionid like :motcle or v.ip like :motcle";
		$oQuery =  $this->_em->createQuery($sSelect);	
		$oQuery->setParameters(array(
			'motcle' => "%".$sTexte."%",
		));	
		$aResult = $oQuery->getResult();
		return $aResult;
	}
}
