<?php

namespace Bo\AdminBundle\Repository;
/**
 * AdminRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTotal(){
		$query = $this->_em->createQuery('SELECT COUNT(a) From BoAdminBundle:Employee a JOIN a.status b WHERE b.id >:1');
		return (int) $query->getSingleScalarResult();
	}
	public function search($sTexte){
		$oEmExp = $this->_em->getRepository('BoAdminBundle:Employee');
		$aResult = $oEmExp->findBy(array('name'=>trim($sTexte)),array('name' => 'desc'));
		if(isset($aResult[0])) return $aResult;
		$oEmExp = $this->_em->getRepository('BoAdminBundle:Employee');
		$aResult = $oEmExp->findBy(array('firstname'=>trim($sTexte)),array('name' => 'desc'));
		if(isset($aResult[0])) return $aResult;
		$aResult = $oEmExp->findBy(array('email'=>$sTexte),array('id' => 'desc'));
		if(isset($aResult[0])) return $aResult;
		$sSelect = "SELECT v FROM Bo\AdminBundle\Entity\Employee v  JOIN v.status u WHERE v.name like :motcle or v.email like :motcle or v.firstname like :motcle or v.homenumber like :motcle or v.address1 like :motcle or u.id >:status";
		$oQuery =  $this->_em->createQuery($sSelect);	
		$oQuery->setParameters(array(
			'motcle' => "%".$sTexte."%",'status'=>1
		));	
		$aResult = $oQuery->getResult();
		return $aResult;
	}
}
