<?php

namespace Bo\AdminBundle\Repository;

/**
 * BillingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillingRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTimesheet($billing){
		$qb = $this->_em->createQueryBuilder();
		$qb->select('a')
			->from('BoAdminBundle:Timesheet', 'a')
			->join('a.billing', 'b')
			->where("b.id =:idbilling and a.status=:status" )
			->setParameters(array('status'=>3,'idbilling'=>$billing->getId()));
		$query = $qb->getQuery();
		$aResult = $query->getResult();	
		return $aResult;
	}
}
