<?php

namespace Bo\AdminBundle\Repository;

/**
 * BillingContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillingContactRepository extends \Doctrine\ORM\EntityRepository
{
}
