<?php

namespace Bo\AdminBundle\Repository;

/**
 * CancelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CancelRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTotal(){
		$query = $this->_em->createQuery('SELECT COUNT(a) From BoAdminBundle:Cancel a');
		return (int) $query->getSingleScalarResult();
	}
	public function getByAgendaAndDate($agenda,$ddate){
		$qb = $this->_em->createQueryBuilder();
		$qb->select('a') 
 			->from('BoAdminBundle:Cancel', 'a')
			->join('a.agenda', 'b')
			->where("b.id=:idagenda and a.startdate <=:ddate and a.enddate >=:ddate" )
			->setParameters(array(
				'idagenda'=>$agenda->getId(),
				'ddate'=>$ddate,
			));
		$query = $qb->getQuery();
		$aResult = $query->getResult();	
		return $aResult;
	}
}
