<?php

namespace Bo\AdminBundle\Repository;

/**
 * CategoryroomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryroomRepository extends \Doctrine\ORM\EntityRepository
{
}
