<?php

namespace Bo\AdminBundle\Repository;

/**
 * CategoryEventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryEventsRepository extends \Doctrine\ORM\EntityRepository
{
}
