<?php

namespace Bo\AdminBundle\Repository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTotal(){
		$query = $this->_em->createQuery('SELECT COUNT(a) From BoAdminBundle:Client a');
		return (int) $query->getSingleScalarResult();
	}
	public function search($sTexte){
		$aTexte = explode(" ",$sTexte);
		$oEmExp = $this->_em->getRepository('BoAdminBundle:Client');
		$aResult = $oEmExp->findBy(array('reference'=>$sTexte),array('id' => 'desc'));
		if(isset($aResult[0])) return $aResult;
		$aResult = $oEmExp->findBy(array('email'=>$sTexte),array('id' => 'desc'));
		if(isset($aResult[0])) return $aResult;
		$sSelect = "SELECT v FROM Bo\AdminBundle\Entity\Client v  JOIN v.typecontract u WHERE v.reference like :motcle or v.email like :motcle or v.designation like :motcle or v.phonenumber like :motcle or v.address like :motcle or u.reference like :motcle or u.designation like :motcle";
		$oQuery =  $this->_em->createQuery($sSelect);	
		$oQuery->setParameters(array(
			'motcle' => "%".$sTexte."%",
		));	
		$aResult = $oQuery->getResult();
		return $aResult;
	}
	public function getContractsList($designation){
		$sSelect = "SELECT v FROM Bo\AdminBundle\Entity\Contracts v  JOIN v.client u WHERE u.designation like :designation";
		$oQuery =  $this->_em->createQuery($sSelect);	
		$oQuery->setParameters(array(
			'designation' => "%".$designation."%",
		));	
		$aResult = $oQuery->getResult();
		return $aResult;
	}
}
