<?php

namespace Bo\AdminBundle\Repository;

/**
 * ContractScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractScheduleRepository extends \Doctrine\ORM\EntityRepository
{
}
