<?php

namespace Bo\AdminBundle\Repository;

/**
 * CoordinatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoordinatorRepository extends \Doctrine\ORM\EntityRepository
{
	public function search($sTexte){
		$aResult=array();	
		$oEmExp = $this->_em->getRepository('BoAdminBundle:Coordinator');
		$aResult = $oEmExp->findByEmail(trim($sTexte));
		if(isset($aResult[0])) return $aResult;
		$aResult = $oEmExp->findByPhone(trim($sTexte));
		if(isset($aResult[0])) return $aResult;	
		$aResult = $this->getByContracttype($sTexte);
		if(isset($aResult[0])) return $aResult;			
		$qb = $this->_em->createQueryBuilder();
		$qb->select('a')
			->from('BoAdminBundle:Coordinator', 'a')
			->where("a.name like :motcle or a.email like :motcle" )
			->setParameter('motcle', "%".trim($sTexte)."%");
		$query = $qb->getQuery();
		return $query->getResult();		
	}
	public function getByContracttype($sTexte){		
		$qb = $this->_em->createQueryBuilder();
		$qb->select('a')
			->from('BoAdminBundle:Coordinator', 'a')
			->join('a.typecontract', 'b')
			->where("b.reference like :motcle" )
			->setParameter('motcle', "%".trim($sTexte)."%");
		$query = $qb->getQuery();
		return $query->getResult();		
	}
}
