<?php

namespace Bo\AdminBundle\Repository;

/**
 * DiaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiaryRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTotal(){
		$query = $this->_em->createQuery('SELECT COUNT(a) From BoAdminBundle:Diary a');
		return (int) $query->getSingleScalarResult();
	}
	public function search($sTexte){
		$aTexte = explode(" ",$sTexte);
		$oEmExp = $this->_em->getRepository('BoAdminBundle:Diary');
		$oResult = $oEmExp->find($sTexte);
		if($oResult) return array($oResult);
		//Search the criteria on employee table
		$aResult = $oEmExp->getByEmployee($sTexte);
		if(isset($aResult[0])) return $aResult;
		//Search the criteria on contract table
		$aResult = $oEmExp->getByContract($sTexte);
		if(isset($aResult[0])) return $aResult;
		//Search the criteria on group table
		$aResult = $oEmExp->getByGroup($sTexte);
		if(isset($aResult[0])) return $aResult;
		//Search the criteria on student table
		$aResult = $oEmExp->getByStudent($sTexte);
		if(isset($aResult[0])) return $aResult;
		$aResult = $this->getByDate($sTexte);
		if(isset($aResult[0])) return $aResult;
		$sSelect = "SELECT v FROM Bo\AdminBundle\Entity\diary v  WHERE v.note like :motcle or v.ddate like :motcle";
		$oQuery =  $this->_em->createQuery($sSelect);	
		$oQuery->setParameters(array(
			'motcle' => "%".$sTexte."%",
		));	
		$aResult = $oQuery->getResult();
		return $aResult;
	}
	private function getByDate($sTexte){
		$aTexte = explode("-",$sTexte);	
		if(count($aTexte)<3) return null;
		if(strlen($aTexte[0])==4) $date=$aTexte[0]."-".$aTexte[1]."-".$aTexte[2];
		if(strlen($aTexte[2])==4) $date=$aTexte[2]."-".$aTexte[1]."-".$aTexte[0];
		$datetime = new \DateTime($sTexte);
		$qb = $this->_em->createQueryBuilder();
		$qb->select('a')
			->from('BoAdminBundle:Diary', 'a')
			->where("a.ddate =:ddate" )
			->setParameters(array('ddate' => $date));
		$query = $qb->getQuery();
		$aResult = $query->getResult();	
		return $aResult;
	}
	private function getByEmployee($sTexte){
		$qb = $this->_em->createQueryBuilder();
		$qb->select('a')
			->from('BoAdminBundle:Diary', 'a')
			->join('a.employee', 'b')
			->where("b.id like :motcle or b.name like :motcle or b.firstname like :motcle" )
			->setParameters(array(
				'motcle'=> "%".trim($sTexte)."%"
				)
			);
		$query = $qb->getQuery();
		return $query->getResult();
	}
	private function getByGroup($sTexte){
		$qb = $this->_em->createQueryBuilder();
		$qb->select('a')
			->from('BoAdminBundle:Diary', 'a')
			->join('a.group', 'b')
			->where("b.id like :motcle or b.name like :motcle" )
			->setParameters(array('motcle'=>"%".trim($sTexte)."%"));
		$query = $qb->getQuery();
		$aResult = $query->getResult();
		return $aResult;
	}
	private function getByContract($sTexte){
		$qb = $this->_em->createQueryBuilder();
		$qb->select('a')
			->from('BoAdminBundle:Diary', 'a')
			->join('a.contracts', 'b')
			->where("b.id=:idcontract or b.startdate like :motcle or b.enddate like :motcle or b.typeoftraining like :motcle or b.ordernumber like :motcle or b.contractnumber like :motcle or b.hourlyrate like :motcle or b.language like :motcle or b.typetime like :motcle or b.reference like :motcle" )
			->setParameters(array('idcontract'=>$sTexte,'motcle'=>"%".trim($sTexte)."%"));
		$query = $qb->getQuery();
		$aResult = $query->getResult();
		return $aResult;
	}
	private function getByStudent($sTexte){
		$qb = $this->_em->createQueryBuilder();
		$qb->select('a')
			->from('BoAdminBundle:Diary', 'a')
			->join('a.students', 'b')
			->where("b.id=:idstudent  or b.name like :motcle or b.firstname like :motcle" )
			->setParameters(array('idstudent'=>$sTexte,'motcle'=>"%".trim($sTexte)."%"));
		$query = $qb->getQuery();
		$aResult = $query->getResult();
		return $aResult;
	}
}
