<?php

namespace Bo\AdminBundle\Repository;

/**
 * DiplomasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiplomasRepository extends \Doctrine\ORM\EntityRepository
{
}
