<?php

namespace Bo\AdminBundle\Repository;

/**
 * emppjRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmppjRepository extends \Doctrine\ORM\EntityRepository
{
}
