<?php

namespace Bo\AdminBundle\Repository;

/**
 * EnquiryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnquiryRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTotal(){
		$query = $this->_em->createQuery('SELECT COUNT(a) From BoAdminBundle:Enquiry a');
		return (int) $query->getSingleScalarResult();
	}
	public function search($sTexte){
		$aResult=array();	
		$qb = $this->_em->createQueryBuilder();
		$qb->select('a')
			->from('BoAdminBundle:Enquiry', 'a')
			->where("a.startdate like :motcle or a.enddate like :motcle or a.name like :motcle or a.firstname like :motcle or a.targetlevel like :motcle or a.phone like :motcle or a.email like :motcle" )
			->setParameter('motcle', "%".$sTexte."%");
		$query = $qb->getQuery();
		$aResult = $query->getResult();	
		return $aResult;	
	}
	public function extrasearch($status){
		$aResult=array();
		$qb = $this->_em->createQueryBuilder();
		$qb->select('a')
			->from('BoAdminBundle:Enquiry', 'a')
			->where("a.status =:status" )
			->setParameter('status', $status);
		$query = $qb->getQuery();
		$aResult = $query->getResult();	
		return $aResult;	
	}
}
