<?php

namespace Bo\AdminBundle\Repository;

/**
 * ErrorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ErrorsRepository extends \Doctrine\ORM\EntityRepository
{
	public function search($sTexte){
		$aTexte = explode(" ",$sTexte);
		$oEmExp = $this->_em->getRepository('BoAdminBundle:Errors');
		$aResult = $oEmExp->findBy(array('code'=>$sTexte),array('id' => 'desc'));
		if(isset($aResult[0])) return $aResult;
		$sSelect = "SELECT v FROM Bo\AdminBundle\Entity\Errors v WHERE v.creationdate like :motcle or v.action like :motcle";
		$oQuery =  $this->_em->createQuery($sSelect);	
		$oQuery->setParameters(array(
			'motcle' => "%".$sTexte."%",
		));	
		$aResult = $oQuery->getResult();
		return $aResult;
	}
}
