<?php

namespace Bo\AdminBundle\Repository;

/**
 * EtatMobiliersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatMobiliersRepository extends \Doctrine\ORM\EntityRepository
{
}
