<?php

namespace Bo\AdminBundle\Repository;

/**
 * EvaluationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTotal(){
		$query = $this->_em->createQuery('SELECT COUNT(a) From BoAdminBundle:Evaluation a');
		return (int) $query->getSingleScalarResult();
	}
	public function getTotalBy($oEvaluator){
		$query = $this->_em->createQuery('SELECT COUNT(a) From BoAdminBundle:Evaluation a WHERE a.evaluator=:evaluator');
		$query->setParameters(array(
			'evaluator'=>$oEvaluator,
		));
		return (int) $query->getSingleScalarResult();
	}
	public function search($motcle){
		$qb = $this->_em->createQueryBuilder();
		$qb->select('a')
			->from('BoAdminBundle:Evaluation', 'a')
			->join('a.evaluator', 'b')
			->where("a.name like :motcle or a.firstname like :motcle or b.name like :motcle or b.firstname like :motcle or a.emailstudent like :motcle or a.phone like :motcle or a.customer like :motcle or a.contact like :motcle or a.phonecontact like :motcle or a.emailcontact like :motcle or a.billingcontact like :motcle or a.billingphone like :motcle or a.billingemail like :motcle" )
			->setParameters(array(
				'motcle' => "%".$motcle."%",
			));	
		$query = $qb->getQuery();
		$aResult = $query->getResult();	
		return $aResult;
	}
}
