<?php

namespace Bo\AdminBundle\Repository;

/**
 * ExtrapayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExtrapayRepository extends \Doctrine\ORM\EntityRepository
{
}
