<?php

namespace Bo\AdminBundle\Repository;

/**
 * HholidayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HholidayRepository extends \Doctrine\ORM\EntityRepository
{
}
