<?php
namespace Bo\AdminBundle\Repository;
/**
 * HistocontractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistocontractRepository extends \Doctrine\ORM\EntityRepository
{

}
