<?php

namespace Bo\AdminBundle\Repository;

/**
 * HnoshowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HnoshowRepository extends \Doctrine\ORM\EntityRepository
{
}
