<?php

namespace Bo\AdminBundle\Repository;

/**
 * HolidayslistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HolidayslistRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTotal(){
		$query = $this->_em->createQuery('SELECT COUNT(a) From BoAdminBundle:Holidayslist a');
		return (int) $query->getSingleScalarResult();
	}
	public function search($sTexte){
		$aResult=array();	
		$oEmExp = $this->_em->getRepository('BoAdminBundle:Holidayslist');
		$aResult = $oEmExp->findByDesignation(trim($sTexte));
		if(isset($aResult[0])) return $aResult;
		$aResult = $oEmExp->findByProvince(trim($sTexte));
		if(isset($aResult[0])) return $aResult;		
		$aResult = $oEmExp->findByCity(trim($sTexte));
		if(isset($aResult[0])) return $aResult;	
		$qb = $this->_em->createQueryBuilder();
		$qb->select('a')
			->from('BoAdminBundle:Holidayslist', 'a')
			->where("a.ddate like :motcle or a.province like :motcle or a.city like :motcle" )
			->setParameter('motcle', "%".trim($sTexte)."%");
		$query = $qb->getQuery();
		return $query->getResult();		
	}
	public function getByDate($oDate){
		$qb = $this->_em->createQueryBuilder();
		$qb->select('a')
			->from('BoAdminBundle:Holidayslist', 'a')
			->where("a.ddate=:ddate" )
			->setParameters(array('ddate'=>$oDate));
		$query = $qb->getQuery();
		return $query->getResult();	
	}
}
