<?php

namespace Bo\AdminBundle\Repository;

/**
 * HothersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HothersRepository extends \Doctrine\ORM\EntityRepository
{
}
