<?php

namespace Bo\AdminBundle\Repository;

/**
 * HteachingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HteachingRepository extends \Doctrine\ORM\EntityRepository
{
}
