<?php

namespace Bo\AdminBundle\Repository;
use Bo\AdminBundle\Entity\HTeacherschedule;

/**
 * HTeacherScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HTeacherScheduleRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTeacherschedule($aTeachers,$contract){
		if(count($aTeachers)==0) return null;
		$aSchedule=array();
		$aIds=array();
		foreach($aTeachers as $oTeacher){
			$aTeaSch = $this->_em->getRepository('BoAdminBundle:HTeacherSchedule')->findBy(array('idcontracts'=>$contract->getId(),'idemployee'=>$oTeacher->getId()));	
			if(isset($aTeaSch[0])){
				$aSchedule[$oTeacher->getId()]=$this->getScheduleDays($aTeaSch[0]);	
				$aIds[$oTeacher->getId()]=$aTeaSch[0]->getId();				
			}		
		}
		return array($aSchedule,$aIds);
	}
	public function getContractTeacherschedule($contract){
		return $this->_em->getRepository('BoAdminBundle:HTeacherSchedule')->findBy(array('idcontracts'=>$contract->getId()));	
	}
	public function recordHistorique($oTeacherSchedule){
		$oHTS = new HTeacherschedule();
		$oHTS->setIdcontracts($oTeacherSchedule->getIdcontracts());
		$oHTS->setIdemployee($oTeacherSchedule->getIdemployee());
		$oHTS->setMonday($oTeacherSchedule->getMonday());
		$oHTS->setWednesday($oTeacherSchedule->getWednesday());
		$oHTS->setThursday($oTeacherSchedule->getThursday());
		$oHTS->setFriday($oTeacherSchedule->getFriday());
		$oHTS->setSaturday($oTeacherSchedule->getSaturday());
		$oHTS->setStartam($oTeacherSchedule->getStartam());	
		$oHTS->setStartpm($oTeacherSchedule->getStartpm());	
		$oHTS->setEndam($oTeacherSchedule->getEndam());	
		$oHTS->setEndpm($oTeacherSchedule->getEndpm());	
		$oHTS->setStartdate($oTeacherSchedule->getStartdate());	
		$oHTS->setEnddate(new \DateTime());			
		$this->_em->persist($oHTS);
		$this->_em->flush();
		return $oHTS;
	}
	public function getScheduleForTeacher($aSTeachers){
		$aResult = array();
		foreach($aSTeachers as $oTeaSch){
			$aResult[$oTeaSch->getId()] = $this->_em->getRepository('BoAdminBundle:Agenda')->getScheduleDays($oTeaSch);
		}
		return $aResult;
	}
}
