<?php

namespace Bo\AdminBundle\Repository;

/**
 * InvitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitationRepository extends \Doctrine\ORM\EntityRepository
{
	public function getByDate($agenda,$category){
		$qb = $this->_em->createQueryBuilder();
		$qb->select('a')
			->from('BoAdminBundle:Invitation', 'a')
			->join('a.agenda', 'b')
			->where("b.id =:idagenda and a.category=:category")
			->setParameters(array('idagenda'=>$agenda->getId(),'category'=>$category));
		$query = $qb->getQuery();
		$aResult = $query->getResult();	
		return $aResult;
	}
	public function getByEmployee($oEmployee){
		$qb = $this->_em->createQueryBuilder();
		$qb->select('a')
			->from('BoAdminBundle:Invitation', 'a')
			->join('a.agenda', 'b')
			->join('b.employee', 'c')
			->where("c.id =:idemployee")
			->setParameters(array('idemployee'=>$oEmployee->getId()));
		$query = $qb->getQuery();
		$aResult = $query->getResult();	
		return $aResult;
	}
	public function getByAgenda($oAgenda){
		$qb = $this->_em->createQueryBuilder();
		$qb->select('a')
			->from('BoAdminBundle:Invitation', 'a')
			->join('a.agenda', 'b')
			->where("b.id =:idagenda")
			->orderBy('a.id','DESC')
			->setParameters(array('idagenda'=>$oAgenda->getId()));
		$query = $qb->getQuery();
		$aResult = $query->getResult();	
		return $aResult;
	}
}
