<?php

namespace Bo\AdminBundle\Repository;

/**
 * StatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAll(){
		return $this->_em->getRepository('BoAdminBundle:Language')->findBy(array(),array('name' => 'asc'));
	}
}
