<?php

namespace Bo\AdminBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTotal(){
		$query = $this->_em->createQuery('SELECT COUNT(a) From BoAdminBundle:Message a');
		return (int) $query->getSingleScalarResult();
	}
	public function search($sTexte){
		$aTexte = explode(" ",$sTexte);
		$sSelect = "SELECT v FROM Bo\AdminBundle\Entity\Message v WHERE v.descfr like :motcle or v.designation like :motcle or v.descen like :motcle or v.dateCreation like :motcle";
		$oQuery =  $this->_em->createQuery($sSelect);	
		$oQuery->setParameters(array(
			'motcle' => "%".$sTexte."%",
		));	
		$aResult = $oQuery->getResult();
		return $aResult;
	}
}
