<?php

namespace Bo\AdminBundle\Repository;

/**
 * MobiliersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MobiliersRepository extends \Doctrine\ORM\EntityRepository
{
}
