<?php

namespace Bo\AdminBundle\Repository;

/**
 * ModelTsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelTsRepository extends \Doctrine\ORM\EntityRepository
{

}
