<?php
namespace Bo\AdminBundle\Repository;
/**
 * LocalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotifAbsenceRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTotal(){
		$query = $this->_em->createQuery('SELECT COUNT(a) From BoAdminBundle:MotifAbsence a');
		return (int) $query->getSingleScalarResult();
	}
	public function getMotifByName($sName){
		$aMotifAbsence=$this->_em->getRepository('BoAdminBundle:MotifAbsence')->findByName($sName);
		if(isset($aMotifAbsence[0])) return $aMotifAbsence[0]->getValue();
		return null;
	}
	//getMotifAbsenceById
	public function getMotifById($id){ 
		$oMotifAbsence=$this->_em->getRepository('BoAdminBundle:MotifAbsence')->find($id);
		if($oMotifAbsence) return $oMotifAbsence->getValue();   
	}
	public function search($sTexte){
		$sSelect = "SELECT v FROM Bo\AdminBundle\Entity\MotifAbsence v  WHERE v.name like :motcle";
		$oQuery =  $this->_em->createQuery($sSelect);	
		$oQuery->setMotifAbsenceeters(array(
			'motcle' => "%".$sTexte."%",
		));	
		$aResult = $oQuery->getResult();
		return $aResult;
	}	
}
