<?php

namespace Bo\AdminBundle\Repository;

/**
 * OrderformRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderformRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTotal(){
		$query = $this->_em->createQuery('SELECT COUNT(a) From BoAdminBundle:Orderform a');
		return (int) $query->getSingleScalarResult();
	}
	public function getHeadsupTotal(){
		$query = $this->_em->createQuery('SELECT COUNT(a) From BoAdminBundle:Orderform a WHERE a.status=2');
		return (int) $query->getSingleScalarResult();
	}
	public function search($sTexte){
		$aResult=array();	
		$qb = $this->_em->createQueryBuilder();
		$qb->select('a')
			->from('BoAdminBundle:Orderform', 'a')
			->join('a.enquiry', 'b')
			->where("b.startdate like :motcle or b.enddate like :motcle or b.name like :motcle or b.firstname like :motcle or b.targetlevel like :motcle or b.phone like :motcle or b.email like :motcle" )
			->setParameter('motcle', "%".$sTexte."%");
		$query = $qb->getQuery();
		$aResult = $query->getResult();	
		return $aResult;	
	}
	public function extrasearch($status){
		$aResult=array();
		$qb = $this->_em->createQueryBuilder();
		$qb->select('a')
			->from('BoAdminBundle:Orderform','a')
			->where("a.status =:status" )
			->setParameter('status', $status);
		$query = $qb->getQuery();
		$aResult = $query->getResult();	
		return $aResult;	
	}
}
