<?php
namespace Bo\AdminBundle\Repository;
/**
 * LocalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParamRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTotal(){
		$query = $this->_em->createQuery('SELECT COUNT(a) From BoAdminBundle:Param a');
		return (int) $query->getSingleScalarResult();
	}
	public function getParamByName($sName){
		$aParam=$this->_em->getRepository('BoAdminBundle:Param')->findByName($sName);
		if(isset($aParam[0])) return $aParam[0]->getValue();
		return null;
	}
	//getParamById
	public function getParamById($id){ 
		$oParam=$this->_em->getRepository('BoAdminBundle:Param')->find($id);
		if($oParam) return $oParam->getValue();   
	}
	//getParam
	public function getParam($sName,$id){ 
		if($this->getParamByName($sName)!=null) return $this->getParamByName($sName);
		if($this->getParamById($id)!=null) return $this->getParamById($id);
		return null;		
	}
	public function search($sTexte){
		$sSelect = "SELECT v FROM Bo\AdminBundle\Entity\Param v  WHERE v.name like :motcle or v.reference like :motcle or v.value like :motcle";
		$oQuery =  $this->_em->createQuery($sSelect);	
		$oQuery->setParameters(array(
			'motcle' => "%".$sTexte."%",
		));	
		$aResult = $oQuery->getResult();
		return $aResult;
	}	
}
