<?php

namespace Bo\AdminBundle\Repository;

/**
 * PayAdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PayAdminRepository extends \Doctrine\ORM\EntityRepository
{
}
