<?php

namespace Bo\AdminBundle\Repository;

/**
 * PeriodPayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodPayRepository extends \Doctrine\ORM\EntityRepository
{
	public function getExistPeriodPay($oTS){
		$qb = $this->_em->createQueryBuilder();
		$qb->select('a')
			->from('BoAdminBundle:PeriodPay', 'a')
			->where("a.startdate <=:ddate and a.enddate >=:ddate" )
			->setParameters(array('ddate'=> $oTS->getDdate()));
		$query = $qb->getQuery();
		return $query->getResult();	
	}
	public function getCurrentPeriodPay(){
		$now = new \DateTime(date("d-m-Y"));
		$qb = $this->_em->createQueryBuilder();
		$qb->select('a')
			->from('BoAdminBundle:PeriodPay', 'a')
			->where("a.startdate <=:ddate and a.enddate >=:ddate" )
			->setParameters(array('ddate'=> $now));
		$query = $qb->getQuery();
		return $query->getResult();	
	}
}
