<?php

namespace Bo\AdminBundle\Repository;

/**
* PricesreferenceRepository
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class PricesreferenceRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTotal(){
		$query = $this->_em->createQuery('SELECT COUNT(a) From BoAdminBundle:Pricesreference a');
		return (int) $query->getSingleScalarResult();
	}
}
