<?php

namespace Bo\AdminBundle\Repository;

/**
* PricesRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class PricesRepository extends \Doctrine\ORM\EntityRepository
{
	public function getPrices($typecontract,$ftorpt,$privateorgroup,$language,$field,$location){
		$aResult=array();	
		$qb = $this->_em->createQueryBuilder();
		$qb->select('a')
			->from('BoAdminBundle:Prices', 'a')
			->join('a.reference', 'b')
			->join('b.typecontract', 'c')
			->join('b.field', 'd')
			->where("c.reference =:typecontract and d.id =:idfield and b.language=:language and b.ftorpt=:ftorpt and b.privateorgroup=:privateorgroup and b.location=:location")
			->setParameters(array(
				'typecontract'=>$typecontract,
				'idfield'=>$field->getId(),
				'language'=>$language,
				'ftorpt'=>$ftorpt,
				'privateorgroup'=>$privateorgroup,
				'location'=>$location,
			));
		$query = $qb->getQuery();
		$aResult = $query->getResult();	
		return $aResult;
	}
	public function getPricesBy($enquiry){
		$typecontract = $enquiry->getTypecontract();
		$field = $enquiry->getField();
		$language = $enquiry->getLanguage();
		$privateorgroup = $enquiry->getPrivateorgroup();
		$ftorpt = $enquiry->getFtorpt();
		$location = $enquiry->getLocation();
		return $this->getPrices($typecontract,$ftorpt,$privateorgroup,$language,$field,$location);
	}
}
