<?php
namespace Bo\AdminBundle\Repository;
/**
 * RobotRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RobotRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTotal(){
		$query = $this->_em->createQuery('SELECT COUNT(a) From BoAdminBundle:Robot a');
		return (int) $query->getSingleScalarResult();
	}
	public function getUsedhour($oRobot){
		$ddate = $oRobot->getDdate()->format("Y-m-d");
		$qb = $this->_em->createQueryBuilder();
		$qb->select('a')
			->from('BoAdminBundle:Usedhour', 'a')
			->where("a.ddate like :ddate")
			->setParameters(array('ddate' => "%".$ddate."%",));
		$query = $qb->getQuery();
		$aResult = $query->getResult();
		return $aResult;
	}
}
