<?php

namespace Bo\AdminBundle\Repository;

/**
 * RoomUseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomUseRepository extends \Doctrine\ORM\EntityRepository
{
}
