<?php

namespace Bo\AdminBundle\Repository;

/**
 * SecurityCoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecurityCoteRepository extends \Doctrine\ORM\EntityRepository
{
	public function search($sTexte){
		$sSelect = "SELECT v FROM Bo\AdminBundle\Entity\SecurityCote v  JOIN v.employee u WHERE u.name like :motcle or u.email like :motcle or u.firstname like :motcle or u.homenumber like :motcle or u.address1 like :motcle or v.requestdate like :motcle or v.receivedate like :motcle or v.expirydate like :motcle";
		$oQuery =  $this->_em->createQuery($sSelect);	
		$oQuery->setParameters(array(
			'motcle' => "%".$sTexte."%",
		));	
		$aResult = $oQuery->getResult();
		return $aResult;
	}
	
}
