<?php

namespace Bo\AdminBundle\Repository;

/**
 * SpecificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecificationRepository extends \Doctrine\ORM\EntityRepository
{

}
