<?php

namespace Bo\AdminBundle\Repository;

/**
 * SubRubricRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubRubricRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAllen($idrubric){
		return $this->_em->getRepository('BoAdminBundle:SubRubric')->findBy(array('idrubric'=>$idrubric),array('nameen' => 'asc'));
	}
	public function getAllfr($idrubric,$idprofil){
		return $this->_em->getRepository('BoAdminBundle:SubRubric')->findBy(array('idrubric'=>$idrubric),array('namefr' => 'asc'));
	}
}
