<?php

namespace Bo\AdminBundle\Repository;

/**
 * SupContractsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupContractsRepository extends \Doctrine\ORM\EntityRepository
{
}
