<?php

namespace Bo\AdminBundle\Repository;

/**
 * TadminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TadminRepository extends \Doctrine\ORM\EntityRepository
{
}
