<?php

namespace Bo\AdminBundle\Repository;

/**
 * TdayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TdayRepository extends \Doctrine\ORM\EntityRepository
{
	public function getDayByLang($sDay,$lang=null){
		if(strtolower($lang)=="fr") $sSelect = "SELECT v FROM Bo\AdminBundle\Entity\Tday v WHERE v.sdayfr like :day";
		else $sSelect = "SELECT v FROM Bo\AdminBundle\Entity\Tday v WHERE v.sdayen like :day";
		$oQuery =  $this->_em->createQuery($sSelect);	
		$oQuery->setParameters(array(
			'day' => "%".$sDay."%",
		));	
		$aResult = $oQuery->getResult();
		return $aResult;			
	}
	public function getInfoDay($sDay){
		if($this->getDayByLang($sDay)) return $this->getDayByLang($sDay);
		if($this->getDayByLang($sDay,"fr")) return $this->getDayByLang($sDay,"fr");
		return null;
	}
	public function getNumberDay($sDay){
		$aDay = $this->getInfoDay($sDay);
		if($aDay) return $aDay[0]->getIday();
		return null;
	}
}
