<?php

namespace Bo\AdminBundle\Repository;

/**
 * TicketContactsRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketContactsRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTotal(){
		$query = $this->_em->createQuery('SELECT COUNT(a) From BoAdminBundle:TicketContacts a');
		return (int) $query->getSingleScalarResult();
	}
}
