<?php

namespace Bo\AdminBundle\Repository;

/**
 * TmonthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TmonthRepository extends \Doctrine\ORM\EntityRepository
{
	public function getMonthByLang($sMonth,$lang=null){
		if(strtolower($lang)=="fr") $sSelect = "SELECT v FROM Bo\AdminBundle\Entity\Tmonth v WHERE v.smonthfr like :month";
		else $sSelect = "SELECT v FROM Bo\AdminBundle\Entity\Tmonth v WHERE v.smonthen like :month";
		$oQuery =  $this->_em->createQuery($sSelect);	
		$oQuery->setParameters(array(
			'month' => "%".$sMonth."%",
		));	
		$aResult = $oQuery->getResult();
		return $aResult;			
	}
	public function getInfoMonth($sMonth){
		if($this->getMonthByLang($sMonth)) return $this->getMonthByLang($sMonth);
		if($this->getMonthByLang($sMonth,"fr")) return $this->getMonthByLang($sMonth,"fr");
		return null;
	}
	public function getNumberMonth($sMonth){
		$aMonth = $this->getInfoMonth($sMonth);
		if($aMonth) return $aMonth[0]->getImonth();
		return null;
	}
}
