<?php

namespace Bo\AdminBundle\Repository;

/**
 * TsBillingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TsBillingRepository extends \Doctrine\ORM\EntityRepository
{
}
