<?php

namespace Bo\AdminBundle\Repository;

/**
 * TsStudentRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TsStudentRepository extends \Doctrine\ORM\EntityRepository
{
	public function getByStudentAndDate($student,$ddate){
		$qb = $this->_em->createQueryBuilder();
		$qb->select('a')
			->from('BoAdminBundle:TsStudent', 'a')
			->join('a.students', 'b')
			->where("b.id=:idstudent and a.ddate=:ddate" )
			->setParameters(array('idstudent'=>$student->getId(),'ddate'=>$ddate));
		$query = $qb->getQuery();
		$aResult = $query->getResult();	
		return $aResult;
	}
	public function getAllBy($aStudents,$ddate){
		$aResult = array();
		foreach($aStudents as $oStudent){
			$aTst = $this->getByStudentAndDate($oStudent,$ddate);
			if(isset($aTst[0])) $aResult[$oStudent->getId()]=$aTst[0];
		}
		return 	$aResult;	
	}
	public function getAttendanceStudent($contract,$yearln,$imonth){
		$aResult = array();
		$aStudents = $contract->getStudents();
		foreach($aStudents as $oStudent){
			$aTsStudent = $this->getTsStudent($oStudent,$yearln,$imonth);
			foreach($aTsStudent as $oTsStudent){
				$oTimesheet = $oTsStudent->getTimesheet();
				$day = $oTimesheet->getDdate()->format("d");
				//A rajouter les périodes de temps AM ou PM
				if($oTsStudent->getLegam()=="ABS"){
					$aResult[$oStudent->getId()][$day]['am'] = "ABS";
				}else{
					$aResult[$oStudent->getId()][$day]['am'] = $oTsStudent->getHam();
				}
				if($oTsStudent->getLegpm()=="ABS"){
					$aResult[$oStudent->getId()][$day]['pm'] = "ABS";
				}else{
					$aResult[$oStudent->getId()][$day]['pm'] = $oTsStudent->getHam();
				}
			}
		}		
		return $aResult;
	}
	public function getTsStudent($oStudent,$yearln,$imonth){
		$aResult = array();
		$qb = $this->_em->createQueryBuilder();
		$qb->select('a')
			->from('BoAdminBundle:TsStudent', 'a')
			->join('a.students', 'b')
			->join('a.timesheet', 'c')	
			->where("c.status > 1 and b.id=:idstudent and a.month=:imonth and a.year=:yearln" )
			->setParameters(array('idstudent'=>$oStudent->getId(),'imonth'=>$imonth,'yearln'=>$yearln));
		$query = $qb->getQuery();
		$aResult = $query->getResult();	
		return $aResult;	
	}
}
