<?php

namespace Bo\AdminBundle\Repository;

/**
 * AbsencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TsValidationRepository extends \Doctrine\ORM\EntityRepository
{
}
