<?php

namespace Bo\AdminBundle\Repository;

/**
 * TtimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TtimeRepository extends \Doctrine\ORM\EntityRepository
{
}
