<?php

namespace Bo\AdminBundle\Repository;

/**
 * TweekRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TweekRepository extends \Doctrine\ORM\EntityRepository
{
}
