<?php

namespace Bo\AdminBundle\Repository;

/**
 * TyearRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TyearRepository extends \Doctrine\ORM\EntityRepository
{
}
