<?php

namespace Bo\AdminBundle\Repository;

/**
 * TypeTeacherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeTeacherRepository extends \Doctrine\ORM\EntityRepository
{
}
