<?php

namespace Bo\AdminBundle\Repository;

/**
 * TypetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypetsRepository extends \Doctrine\ORM\EntityRepository
{
}
