<?php
namespace Bo\AdminBundle\Repository;
/**
 * UsedhourRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsedhourRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTotal(){
		$query = $this->_em->createQuery('SELECT COUNT(a) From BoAdminBundle:Usedhour a');
		return (int) $query->getSingleScalarResult();
	}
}
