<?php

namespace Bo\AdminBundle\Repository;

/**
 * UserMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserMessageRepository extends \Doctrine\ORM\EntityRepository
{

}
