<?php

namespace Bo\AdminBundle\Repository;

/**
 * CampusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkfieldsRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAllField(){
		return $this->_em->getRepository('BoAdminBundle:Workfields')->findBy(array(),array('wfname' => 'asc'));
	}
}
