<?php

namespace Bo\AdminBundle\Repository;

/**
 * InvitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitationRepository extends \Doctrine\ORM\EntityRepository
{
	public function getByDate($agenda,$category,$today){
		$qb = $this->_em->createQueryBuilder();
		$qb->select('a')
			->from('BoAdminBundle:Invitation', 'a')
			->join('a.agenda', 'b')
			->where("b.id =:idagenda and a.creationdate like :today and a.category=:category")
			->setParameters(array('idagenda'=>$agenda->getId(),'category'=>$category,'today'=>$today));
		$query = $qb->getQuery();
		$aResult = $query->getResult();	
		return $aResult;
	}
}
