evaluation_index:
    path:     /
    defaults: { _controller: "BoQuizBundle:Evaluation:index" }
    methods:  GET

evaluation_show:
    path:     /{id}/show
    defaults: { _controller: "BoQuizBundle:Evaluation:show" }
    methods:  GET

evaluation_new:
    path:     /new
    defaults: { _controller: "BoQuizBundle:Evaluation:new" }
    methods:  [GET, POST]

evaluation_edit:
    path:     /{id}/edit
    defaults: { _controller: "BoQuizBundle:Evaluation:edit" }
    methods:  [GET, POST]

evaluation_delete:
    path:     /{id}/delete
    defaults: { _controller: "BoQuizBundle:Evaluation:delete" }
    methods:  DELETE
