resultsquiz_index:
    path:     /
    defaults: { _controller: "BoQuizBundle:Resultsquiz:index" }
    methods:  GET

resultsquiz_show:
    path:     /{id}/show
    defaults: { _controller: "BoQuizBundle:Resultsquiz:show" }
    methods:  GET

resultsquiz_new:
    path:     /new
    defaults: { _controller: "BoQuizBundle:Resultsquiz:new" }
    methods:  [GET, POST]

resultsquiz_edit:
    path:     /{id}/edit
    defaults: { _controller: "BoQuizBundle:Resultsquiz:edit" }
    methods:  [GET, POST]

resultsquiz_delete:
    path:     /{id}/delete
    defaults: { _controller: "BoQuizBundle:Resultsquiz:delete" }
    methods:  DELETE
