<?php

namespace Proxies\__CG__\Bo\AdminBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Timesheet extends \Bo\AdminBundle\Entity\Timesheet implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'id', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'employee', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'group', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'students', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'contract', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'tsweek', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'ddate', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'startam', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'endam', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'startpm', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'endpm', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'hour', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'teacherns', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'studentns', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'legende', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'month', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'year', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'typets', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'idperiodpay', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'idstudentabsence', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'amorpm', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'billing', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'status', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'note', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'creationdate'];
        }

        return ['__isInitialized__', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'id', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'employee', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'group', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'students', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'contract', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'tsweek', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'ddate', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'startam', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'endam', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'startpm', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'endpm', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'hour', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'teacherns', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'studentns', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'legende', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'month', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'year', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'typets', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'idperiodpay', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'idstudentabsence', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'amorpm', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'billing', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'status', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'note', '' . "\0" . 'Bo\\AdminBundle\\Entity\\Timesheet' . "\0" . 'creationdate'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Timesheet $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartam($startam)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartam', [$startam]);

        return parent::setStartam($startam);
    }

    /**
     * {@inheritDoc}
     */
    public function getStartam()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartam', []);

        return parent::getStartam();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndam($endam)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndam', [$endam]);

        return parent::setEndam($endam);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndam()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndam', []);

        return parent::getEndam();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartpm($startpm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartpm', [$startpm]);

        return parent::setStartpm($startpm);
    }

    /**
     * {@inheritDoc}
     */
    public function getStartpm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartpm', []);

        return parent::getStartpm();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndpm($endpm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndpm', [$endpm]);

        return parent::setEndpm($endpm);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndpm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndpm', []);

        return parent::getEndpm();
    }

    /**
     * {@inheritDoc}
     */
    public function setHour($hour)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHour', [$hour]);

        return parent::setHour($hour);
    }

    /**
     * {@inheritDoc}
     */
    public function getHour()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHour', []);

        return parent::getHour();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreationdate($creationdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreationdate', [$creationdate]);

        return parent::setCreationdate($creationdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreationdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreationdate', []);

        return parent::getCreationdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDdate($ddate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDdate', [$ddate]);

        return parent::setDdate($ddate);
    }

    /**
     * {@inheritDoc}
     */
    public function getDdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDdate', []);

        return parent::getDdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setLegende($legende)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLegende', [$legende]);

        return parent::setLegende($legende);
    }

    /**
     * {@inheritDoc}
     */
    public function getLegende()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLegende', []);

        return parent::getLegende();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmployee(\Bo\AdminBundle\Entity\Employee $employee = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmployee', [$employee]);

        return parent::setEmployee($employee);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmployee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmployee', []);

        return parent::getEmployee();
    }

    /**
     * {@inheritDoc}
     */
    public function setContract(\Bo\AdminBundle\Entity\Contracts $contract = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContract', [$contract]);

        return parent::setContract($contract);
    }

    /**
     * {@inheritDoc}
     */
    public function getContract()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContract', []);

        return parent::getContract();
    }

    /**
     * {@inheritDoc}
     */
    public function setTsweek(\Bo\AdminBundle\Entity\Tsweek $tsweek = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTsweek', [$tsweek]);

        return parent::setTsweek($tsweek);
    }

    /**
     * {@inheritDoc}
     */
    public function getTsweek()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTsweek', []);

        return parent::getTsweek();
    }

    /**
     * {@inheritDoc}
     */
    public function setGroup(\Bo\AdminBundle\Entity\Group $group = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGroup', [$group]);

        return parent::setGroup($group);
    }

    /**
     * {@inheritDoc}
     */
    public function getGroup()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroup', []);

        return parent::getGroup();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStudents(\Bo\AdminBundle\Entity\Students $students = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStudents', [$students]);

        return parent::setStudents($students);
    }

    /**
     * {@inheritDoc}
     */
    public function getStudents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStudents', []);

        return parent::getStudents();
    }

    /**
     * {@inheritDoc}
     */
    public function setNextStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNextStatus', []);

        return parent::setNextStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getNextStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNextStatus', []);

        return parent::getNextStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setRejectStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRejectStatus', []);

        return parent::setRejectStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getRejectStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRejectStatus', []);

        return parent::getRejectStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setInitialStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInitialStatus', []);

        return parent::setInitialStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getInitialStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInitialStatus', []);

        return parent::getInitialStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setValidatedStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValidatedStatus', []);

        return parent::setValidatedStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getValidatedStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValidatedStatus', []);

        return parent::getValidatedStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setOthersStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOthersStatus', []);

        return parent::setOthersStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getOthersStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOthersStatus', []);

        return parent::getOthersStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayrollStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayrollStatus', []);

        return parent::setPayrollStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaidStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaidStatus', []);

        return parent::setPaidStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingStatus', []);

        return parent::setBillingStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setAmorpm($amorpm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAmorpm', [$amorpm]);

        return parent::setAmorpm($amorpm);
    }

    /**
     * {@inheritDoc}
     */
    public function getAmorpm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAmorpm', []);

        return parent::getAmorpm();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdperiodpay($idperiodpay)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdperiodpay', [$idperiodpay]);

        return parent::setIdperiodpay($idperiodpay);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdperiodpay()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdperiodpay', []);

        return parent::getIdperiodpay();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypets(\Bo\AdminBundle\Entity\Typets $typets = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypets', [$typets]);

        return parent::setTypets($typets);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypets()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypets', []);

        return parent::getTypets();
    }

    /**
     * {@inheritDoc}
     */
    public function addBilling(\Bo\AdminBundle\Entity\Billing $billing)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBilling', [$billing]);

        return parent::addBilling($billing);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBilling(\Bo\AdminBundle\Entity\Billing $billing)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBilling', [$billing]);

        return parent::removeBilling($billing);
    }

    /**
     * {@inheritDoc}
     */
    public function getBilling()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBilling', []);

        return parent::getBilling();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatusDefinition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatusDefinition', []);

        return parent::getStatusDefinition();
    }

    /**
     * {@inheritDoc}
     */
    public function setMonth($month)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMonth', [$month]);

        return parent::setMonth($month);
    }

    /**
     * {@inheritDoc}
     */
    public function getMonth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMonth', []);

        return parent::getMonth();
    }

    /**
     * {@inheritDoc}
     */
    public function setYear($year)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYear', [$year]);

        return parent::setYear($year);
    }

    /**
     * {@inheritDoc}
     */
    public function getYear()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYear', []);

        return parent::getYear();
    }

    /**
     * {@inheritDoc}
     */
    public function setNote($note)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNote', [$note]);

        return parent::setNote($note);
    }

    /**
     * {@inheritDoc}
     */
    public function getNote()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNote', []);

        return parent::getNote();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoshow($noshow)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoshow', [$noshow]);

        return parent::setNoshow($noshow);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoshow()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoshow', []);

        return parent::getNoshow();
    }

    /**
     * {@inheritDoc}
     */
    public function setTeacherns($teacherns)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTeacherns', [$teacherns]);

        return parent::setTeacherns($teacherns);
    }

    /**
     * {@inheritDoc}
     */
    public function getTeacherns()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTeacherns', []);

        return parent::getTeacherns();
    }

    /**
     * {@inheritDoc}
     */
    public function setStudentns($studentns)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStudentns', [$studentns]);

        return parent::setStudentns($studentns);
    }

    /**
     * {@inheritDoc}
     */
    public function getStudentns()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStudentns', []);

        return parent::getStudentns();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdstudentabsence($idstudentabsence)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdstudentabsence', [$idstudentabsence]);

        return parent::setIdstudentabsence($idstudentabsence);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdstudentabsence()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdstudentabsence', []);

        return parent::getIdstudentabsence();
    }

}
