campus_index:
    path:     /
    defaults: { _controller: "BoAdminBundle:Campus:index" }
    methods:  GET

campus_show:
    path:     /{id}/show
    defaults: { _controller: "BoAdminBundle:Campus:show" }
    methods:  GET

campus_new:
    path:     /new
    defaults: { _controller: "BoAdminBundle:Campus:new" }
    methods:  [GET, POST]

campus_edit:
    path:     /{id}/edit
    defaults: { _controller: "BoAdminBundle:Campus:edit" }
    methods:  [GET, POST]

campus_delete:
    path:     /{id}/delete
    defaults: { _controller: "BoAdminBundle:Campus:delete" }
    methods:  DELETE
