categoryroom_index:
    path:     /
    defaults: { _controller: "BoAdminBundle:Categoryroom:index" }
    methods:  GET

categoryroom_show:
    path:     /{id}/show
    defaults: { _controller: "BoAdminBundle:Categoryroom:show" }
    methods:  GET

categoryroom_new:
    path:     /new
    defaults: { _controller: "BoAdminBundle:Categoryroom:new" }
    methods:  [GET, POST]

categoryroom_edit:
    path:     /{id}/edit
    defaults: { _controller: "BoAdminBundle:Categoryroom:edit" }
    methods:  [GET, POST]

categoryroom_delete:
    path:     /{id}/delete
    defaults: { _controller: "BoAdminBundle:Categoryroom:delete" }
    methods:  DELETE
