documents_index:
    path:     /
    defaults: { _controller: "BoAdminBundle:Documents:index" }
    methods:  GET

documents_show:
    path:     /{id}/show
    defaults: { _controller: "BoAdminBundle:Documents:show" }
    methods:  GET

documents_new:
    path:     /new
    defaults: { _controller: "BoAdminBundle:Documents:new" }
    methods:  [GET, POST]

documents_edit:
    path:     /{id}/edit
    defaults: { _controller: "BoAdminBundle:Documents:edit" }
    methods:  [GET, POST]

documents_delete:
    path:     /{id}/delete
    defaults: { _controller: "BoAdminBundle:Documents:delete" }
    methods:  DELETE
