hholiday_index:
    path:     /
    defaults: { _controller: "BoAdminBundle:Hholiday:index" }
    methods:  GET

hholiday_show:
    path:     /{id}/show
    defaults: { _controller: "BoAdminBundle:Hholiday:show" }
    methods:  GET

hholiday_new:
    path:     /new
    defaults: { _controller: "BoAdminBundle:Hholiday:new" }
    methods:  [GET, POST]

hholiday_edit:
    path:     /{id}/edit
    defaults: { _controller: "BoAdminBundle:Hholiday:edit" }
    methods:  [GET, POST]

hholiday_delete:
    path:     /{id}/delete
    defaults: { _controller: "BoAdminBundle:Hholiday:delete" }
    methods:  DELETE
