level_index:
    path:     /
    defaults: { _controller: "BoAdminBundle:Level:index" }
    methods:  GET

level_show:
    path:     /{id}/show
    defaults: { _controller: "BoAdminBundle:Level:show" }
    methods:  GET

level_new:
    path:     /new
    defaults: { _controller: "BoAdminBundle:Level:new" }
    methods:  [GET, POST]

level_edit:
    path:     /{id}/edit
    defaults: { _controller: "BoAdminBundle:Level:edit" }
    methods:  [GET, POST]

level_delete:
    path:     /{id}/delete
    defaults: { _controller: "BoAdminBundle:Level:delete" }
    methods:  DELETE
