mails_index:
    path:     /
    defaults: { _controller: "BoAdminBundle:Mails:index" }
    methods:  GET

mails_show:
    path:     /{id}/show
    defaults: { _controller: "BoAdminBundle:Mails:show" }
    methods:  GET

mails_new:
    path:     /new
    defaults: { _controller: "BoAdminBundle:Mails:new" }
    methods:  [GET, POST]

mails_edit:
    path:     /{id}/edit
    defaults: { _controller: "BoAdminBundle:Mails:edit" }
    methods:  [GET, POST]

mails_delete:
    path:     /{id}/delete
    defaults: { _controller: "BoAdminBundle:Mails:delete" }
    methods:  DELETE
