modelts_index:
    path:     /
    defaults: { _controller: "BoAdminBundle:ModelTs:index" }
    methods:  GET

modelts_show:
    path:     /{id}/show
    defaults: { _controller: "BoAdminBundle:ModelTs:show" }
    methods:  GET

modelts_new:
    path:     /new
    defaults: { _controller: "BoAdminBundle:ModelTs:new" }
    methods:  [GET, POST]

modelts_edit:
    path:     /{id}/edit
    defaults: { _controller: "BoAdminBundle:ModelTs:edit" }
    methods:  [GET, POST]

modelts_delete:
    path:     /{id}/delete
    defaults: { _controller: "BoAdminBundle:ModelTs:delete" }
    methods:  DELETE
