param_index:
    path:     /
    defaults: { _controller: "BoAdminBundle:Param:index" }
    methods:  GET
param_list:
    path:     /list/
    defaults: { _controller: "BoAdminBundle:Param:list" }
    methods:  GET
param_page:
    path:     /page/{option}
    defaults: { _controller: "BoAdminBundle:Param:page" }
param_show:
    path:     /{id}/show
    defaults: { _controller: "BoAdminBundle:Param:show" }
    methods:  GET
param_new:
    path:     /new
    defaults: { _controller: "BoAdminBundle:Param:new" }
    methods:  [GET, POST]
param_edit:
    path:     /{id}/edit
    defaults: { _controller: "BoAdminBundle:Param:edit" }
    methods:  [GET, POST]
param_delete:
    path:     /{id}/delete
    defaults: { _controller: "BoAdminBundle:Param:delete" }
    methods:  DELETE
param_search:
    path:  /search/
    defaults: { _controller: "BoAdminBundle:Param:search" }
    methods:  [GET, POST]
param_pagesearch:
    path:  /pagesearch/
    defaults: { _controller: "BoAdminBundle:Param:pagesearch" }
    methods:  [GET, POST]
