profil_index:
    path:     /
    defaults: { _controller: "BoAdminBundle:Profil:index" }
    methods:  GET
profil_show:
    path:     /{id}/show
    defaults: { _controller: "BoAdminBundle:Profil:show" }
    methods:  GET
profil_all_enable:
    path:     /{id}/{action}/allenable
    defaults: { _controller: "BoAdminBundle:Profil:allenable" }
    methods:  GET
profil_enableall:
    path:     /{id}/enable/all
    defaults: { _controller: "BoAdminBundle:Profil:enableall" }
    methods:  GET
profil_new:
    path:     /new
    defaults: { _controller: "BoAdminBundle:Profil:new" }
    methods:  [GET, POST]
profil_edit:
    path:     /{id}/edit
    defaults: { _controller: "BoAdminBundle:Profil:edit" }
    methods:  [GET, POST]
profil_delete:
    path:     /{id}/delete
    defaults: { _controller: "BoAdminBundle:Profil:delete" }
    methods:  DELETE
profil_srubric_load:
    path:     /rubric/reload/
    defaults: { _controller: "BoAdminBundle:Profil:srubric" }
    methods:  [GET, POST]
