<?php

namespace Bo\QuizBundle\Repository;

/**
 * ScoringRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScoringRepository extends \Doctrine\ORM\EntityRepository
{
}
