<?php

namespace Bo\UserBundle\Repository;

/**
 * RightsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RightsRepository extends \Doctrine\ORM\EntityRepository
{
	public function removeRights($idprofil){
		$qb = $this->_em->createQueryBuilder()
			->delete('BoUserBundle:Rights','a')
			->where('a.idprofil =:idprofil')
			->setParameter('idprofil',$idprofil)
			->getQuery();
		return $qb->execute();	
	}
}
