home_absences_index:
    path:     /
    defaults: { _controller: "BoHomeBundle:Absences:index" }
    methods:  GET
home_absences_show:
    path:     /{id}/show
    defaults: { _controller: "BoHomeBundle:Absences:show" }
    methods:  GET
home_absences_new:
    path:     /new
    defaults: { _controller: "BoHomeBundle:Absences:new" }
    methods:  [GET, POST]
home_absences_edit:
    path:     /{id}/edit
    defaults: { _controller: "BoHomeBundle:Absences:edit" }
    methods:  [GET, POST]
home_absences_delete:
    path:     /{id}/delete
    defaults: { _controller: "BoHomeBundle:Absences:delete" }
    methods:  DELETE
