home_emppj_index:
    path:     /
    defaults: { _controller: "BoHomeBundle:Emppj:index" }
    methods:  GET
home_emppj_show:
    path:     /{id}/show
    defaults: { _controller: "BoHomeBundle:Emppj:show" }
    methods:  GET
home_emppj_new:
    path:     /new
    defaults: { _controller: "BoHomeBundle:Emppj:new" }
    methods:  [GET, POST]
home_emppj_edit:
    path:     /{id}/edit
    defaults: { _controller: "BoHomeBundle:Emppj:edit" }
    methods:  [GET, POST]
home_emppj_delete:
    path:     /{id}/delete
    defaults: { _controller: "BoHomeBundle:Emppj:delete" }
    methods:  DELETE
