home_message_index:
    path:     /
    defaults: { _controller: "BoHomeBundle:Message:index" }
    methods:  GET
home_message_show:
    path:     /{id}/show
    defaults: { _controller: "BoHomeBundle:Message:show" }
    methods:  GET
home_message_new:
    path:     /new
    defaults: { _controller: "BoHomeBundle:Message:new" }
    methods:  [GET, POST]
home_message_edit:
    path:     /{id}/edit
    defaults: { _controller: "BoHomeBundle:Message:edit" }
    methods:  [GET, POST]
home_message_delete:
    path:     /{id}/delete
    defaults: { _controller: "BoHomeBundle:Message:delete" }
    methods:  DELETE
